// <auto-generated />
using System;
using MagicVilla_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(VillaContext))]
    partial class VillaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Fee")
                        .HasColumnType("real");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupants")
                        .HasColumnType("int");

                    b.Property<float>("SquareMeters")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Amenity 1",
                            CreationDate = new DateTime(2023, 4, 3, 15, 3, 33, 576, DateTimeKind.Local).AddTicks(2506),
                            Detail = "Villa detail 1",
                            Fee = 1f,
                            ImageUrl = "",
                            Name = "Villa 1",
                            Occupants = 10,
                            SquareMeters = 80.5f,
                            UpdateDate = new DateTime(2023, 4, 3, 15, 3, 33, 576, DateTimeKind.Local).AddTicks(2524)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Amenity 2",
                            CreationDate = new DateTime(2023, 4, 3, 15, 3, 33, 576, DateTimeKind.Local).AddTicks(2535),
                            Detail = "Villa detail 2",
                            Fee = 2f,
                            ImageUrl = "",
                            Name = "Villa 2",
                            Occupants = 20,
                            SquareMeters = 200f,
                            UpdateDate = new DateTime(2023, 4, 3, 15, 3, 33, 576, DateTimeKind.Local).AddTicks(2536)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Amenity 3",
                            CreationDate = new DateTime(2023, 4, 3, 15, 3, 33, 576, DateTimeKind.Local).AddTicks(2540),
                            Detail = "Villa detail 3",
                            Fee = 3f,
                            ImageUrl = "",
                            Name = "Villa 3",
                            Occupants = 30,
                            SquareMeters = 300f,
                            UpdateDate = new DateTime(2023, 4, 3, 15, 3, 33, 576, DateTimeKind.Local).AddTicks(2541)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Amenity 4",
                            CreationDate = new DateTime(2023, 4, 3, 15, 3, 33, 576, DateTimeKind.Local).AddTicks(2545),
                            Detail = "Villa detail 4",
                            Fee = 4f,
                            ImageUrl = "",
                            Name = "Villa 4",
                            Occupants = 40,
                            SquareMeters = 400f,
                            UpdateDate = new DateTime(2023, 4, 3, 15, 3, 33, 576, DateTimeKind.Local).AddTicks(2546)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Amenity 5",
                            CreationDate = new DateTime(2023, 4, 3, 15, 3, 33, 576, DateTimeKind.Local).AddTicks(2549),
                            Detail = "Villa detail 5",
                            Fee = 5f,
                            ImageUrl = "",
                            Name = "Villa 5",
                            Occupants = 50,
                            SquareMeters = 500f,
                            UpdateDate = new DateTime(2023, 4, 3, 15, 3, 33, 576, DateTimeKind.Local).AddTicks(2550)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
